### ISSUE TITLE
Feedback for “Using Fabric API Events”

### ISSUE THREAD

**Issue by ToBinio** [moddedmc-wiki/fabric-modding-wiki#60]
the explanation of the ActionResults feels confusing and could it be that Success and FAIL are switched?

|Type|Affect|
|----|---------------|
|`ActionResult.SUCCESS`|Cancels all other listeners, cancels the attack as well.|
|`ActionResult.PASS`|Do not do anything else.|
|`ActionResult.FAIL`|Cancel all other listeners, but don't cancel the attack.|

I believe using the wording of the fabric itself would be better

|Type|Affect|
|----|---------------|
|`ActionResult.SUCCESS`|cancels further processing and, on the client, sends a packet to the server.|
|`ActionResult.PASS`|falls back to further processing.|
|`ActionResult.FAIL`|cancels further processing and does not send a packet to the server.|

note:
thanks for the great work with the whole wiki helps a lot

note 2:
if you are ok with this change I should be to able open a PR myself (in case of this helps)

**Comment by mineblock11** [comment]
> if you are ok with this change I should be to able open a PR myself (in case of this helps)
You can make a pull request, this would be really helpful :+1: (just make sure your grammar is correct and capitalize stuff, LanguageTool is really good for this)
