### ISSUE TITLE
[Feature] Make image big when clicked

### ISSUE THREAD

**Issue by agent-LuluDodo** [moddedmc-wiki/fabric-modding-wiki#69]
Some of your pages have images with tiny text (especially https://fabric.moddedmc.wiki/getting-started/basic-problem-solving). It would be nice if the image popped up when clicked. The [Minecraft Wiki](https://minecraft.wiki) does this nicely, for example.

**Comment by IMB11** [comment]
I'm actually investigating something for this at the moment, I'll keep you updated.

**Comment by IMB11** [comment]
Added
